import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const require = createRequire(import.meta.url);
const {
  buildRuntimeConfig,
  renderRuntimeSources
} = require("../scripts/generate-runtime-config.cjs") as {
  buildRuntimeConfig(environment: Record<string, string | undefined>): {
    mode: "local" | "acceptance" | "production";
    apiBase: string;
  };
  renderRuntimeSources(config: { mode: string; apiBase: string }): {
    javascript: string;
    typescript: string;
  };
};

type GeneratorFixture = {
  configDirectory: string;
  scriptPath: string;
};

function withGeneratorFixture(test: (fixture: GeneratorFixture) => void) {
  const root = mkdtempSync(join(tmpdir(), "photo-ai-runtime-generator-"));
  const scriptsDirectory = join(root, "scripts");
  const configDirectory = join(root, "miniprogram", "config");
  mkdirSync(scriptsDirectory, { recursive: true });
  const scriptPath = join(scriptsDirectory, "generate-runtime-config.cjs");
  copyFileSync(
    fileURLToPath(new URL("../scripts/generate-runtime-config.cjs", import.meta.url)),
    scriptPath
  );
  try {
    test({ configDirectory, scriptPath });
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
}

function runGenerator(
  fixture: GeneratorFixture,
  command: "--local" | "--from-env" | "--ensure",
  environment: Record<string, string> = {},
  preloadPath?: string
) {
  const args = preloadPath ? [
    "--require",
    preloadPath,
    fixture.scriptPath,
    command
  ] : [fixture.scriptPath, command];
  return spawnSync(process.execPath, args, {
    encoding: "utf8",
    env: { ...process.env, ...environment }
  });
}

function generatedFiles(fixture: GeneratorFixture) {
  return {
    javascript: readFileSync(
      join(fixture.configDirectory, "runtime.generated.js"),
      "utf8"
    ),
    typescript: readFileSync(
      join(fixture.configDirectory, "runtime.generated.ts"),
      "utf8"
    )
  };
}

describe("runtime config generator", () => {
  it("writes deterministic local TypeScript and JavaScript without temp files", () => {
    withGeneratorFixture((fixture) => {
      expect(runGenerator(fixture, "--local").status).toBe(0);
      const first = generatedFiles(fixture);
      expect(first).toEqual({
        javascript: "// Generated by scripts/generate-runtime-config.cjs. Do not edit or commit.\n" +
          "// Generation: a0eb549e6c68ce46a6db82b3bca663a6a1987a7e4a6603c4de18b2fa11038901\n" +
          "export const runtimeConfig = Object.freeze({\n" +
          "  mode: \"local\",\n" +
          "  apiBase: \"http://127.0.0.1:3100\"\n" +
          "});\n",
        typescript: "// Generated by scripts/generate-runtime-config.cjs. Do not edit or commit.\n" +
          "// Generation: a0eb549e6c68ce46a6db82b3bca663a6a1987a7e4a6603c4de18b2fa11038901\n" +
          "export const runtimeConfig = Object.freeze({\n" +
          "  mode: \"local\",\n" +
          "  apiBase: \"http://127.0.0.1:3100\"\n" +
          "} as const);\n"
      });

      expect(runGenerator(fixture, "--local").status).toBe(0);
      expect(generatedFiles(fixture)).toEqual(first);
      expect(readdirSync(fixture.configDirectory).toSorted()).toEqual([
        "runtime.generated.js",
        "runtime.generated.ts"
      ]);
    });
  });

  it("writes the same validated acceptance config to TypeScript and JavaScript", () => {
    withGeneratorFixture((fixture) => {
      const result = runGenerator(fixture, "--from-env", {
        PHOTO_AI_APP_MODE: "acceptance",
        PHOTO_AI_API_BASE: "http://192.168.1.20:3100/"
      });

      expect(result.status).toBe(0);
      expect(generatedFiles(fixture)).toEqual({
        javascript: "// Generated by scripts/generate-runtime-config.cjs. Do not edit or commit.\n" +
          "// Generation: b48783847f93911077588ceb021e96c2dcf3cd954dcac69301f20cf40f8d3fae\n" +
          "export const runtimeConfig = Object.freeze({\n" +
          "  mode: \"acceptance\",\n" +
          "  apiBase: \"http://192.168.1.20:3100\"\n" +
          "});\n",
        typescript: "// Generated by scripts/generate-runtime-config.cjs. Do not edit or commit.\n" +
          "// Generation: b48783847f93911077588ceb021e96c2dcf3cd954dcac69301f20cf40f8d3fae\n" +
          "export const runtimeConfig = Object.freeze({\n" +
          "  mode: \"acceptance\",\n" +
          "  apiBase: \"http://192.168.1.20:3100\"\n" +
          "} as const);\n"
      });
    });
  });

  it("preserves both configured files when ensure sees a complete pair", () => {
    withGeneratorFixture((fixture) => {
      expect(runGenerator(fixture, "--from-env", {
        PHOTO_AI_APP_MODE: "acceptance",
        PHOTO_AI_API_BASE: "http://10.20.30.40:3100"
      }).status).toBe(0);
      const configured = generatedFiles(fixture);

      expect(runGenerator(fixture, "--ensure").status).toBe(0);

      expect(generatedFiles(fixture)).toEqual(configured);
      expect(configured.javascript).toContain('mode: "acceptance"');
      expect(configured.typescript).toContain('apiBase: "http://10.20.30.40:3100"');
    });
  });

  it("repairs an acceptance TypeScript and local JavaScript split pair", () => {
    withGeneratorFixture((fixture) => {
      expect(runGenerator(fixture, "--from-env", {
        PHOTO_AI_APP_MODE: "acceptance",
        PHOTO_AI_API_BASE: "http://192.168.1.20:3100"
      }).status).toBe(0);
      const acceptance = generatedFiles(fixture);
      expect(runGenerator(fixture, "--local").status).toBe(0);
      const local = generatedFiles(fixture);
      writeFileSync(
        join(fixture.configDirectory, "runtime.generated.ts"),
        acceptance.typescript
      );

      expect(runGenerator(fixture, "--ensure").status).toBe(0);

      expect(generatedFiles(fixture)).toEqual(local);
      expect(readdirSync(fixture.configDirectory).toSorted()).toEqual([
        "runtime.generated.js",
        "runtime.generated.ts"
      ]);
    });
  });

  it("rolls back the first replacement when the JavaScript rename fails", () => {
    withGeneratorFixture((fixture) => {
      expect(runGenerator(fixture, "--local").status).toBe(0);
      const original = generatedFiles(fixture);
      const injectorPath = join(fixture.configDirectory, "..", "rename-failure.cjs");
      writeFileSync(injectorPath, `
const fs = require("node:fs");
const renameSync = fs.renameSync;
let injected = false;
fs.renameSync = function (source, target) {
  if (!injected && source.includes(".tmp") && target.endsWith("runtime.generated.js")) {
    injected = true;
    throw new Error("INJECTED_SECOND_RENAME_FAILURE");
  }
  return renameSync.call(this, source, target);
};
`);

      const result = runGenerator(fixture, "--from-env", {
        PHOTO_AI_APP_MODE: "acceptance",
        PHOTO_AI_API_BASE: "http://192.168.1.20:3100"
      }, injectorPath);

      expect(result.status).toBe(1);
      expect(result.stderr).toContain("INJECTED_SECOND_RENAME_FAILURE");
      expect(generatedFiles(fixture)).toEqual(original);
      expect(readdirSync(fixture.configDirectory).toSorted()).toEqual([
        "runtime.generated.js",
        "runtime.generated.ts"
      ]);
    });
  });

  it("JSON-escapes both source formats from one config", () => {
    const apiBase = 'https://example.com/"\\\n';

    const sources = renderRuntimeSources({ mode: "acceptance", apiBase });

    const escaped = JSON.stringify(apiBase);
    expect(sources.typescript).toContain(`apiBase: ${escaped}`);
    expect(sources.javascript).toContain(`apiBase: ${escaped}`);
  });

  it("requires an explicit API base when invoked from the environment", () => {
    const environment = {
      ...process.env,
      PHOTO_AI_APP_MODE: "local"
    };
    delete environment.PHOTO_AI_API_BASE;

    const result = spawnSync(process.execPath, [
      fileURLToPath(new URL("../scripts/generate-runtime-config.cjs", import.meta.url)),
      "--from-env"
    ], {
      encoding: "utf8",
      env: environment
    });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("INVALID_PHOTO_AI_API_BASE");
  });

  it("uses localhost only in local mode", () => {
    expect(buildRuntimeConfig({ PHOTO_AI_APP_MODE: "local" })).toEqual({
      mode: "local",
      apiBase: "http://127.0.0.1:3100"
    });
  });

  it.each([
    ["10.0.0.1", "http://10.0.0.1:3100"],
    ["10.255.255.255", "http://10.255.255.255:3100"],
    ["172.16.0.1", "http://172.16.0.1:3100"],
    ["172.31.255.255", "http://172.31.255.255:3100"],
    ["192.168.0.1", "http://192.168.0.1:3100"],
    ["192.168.255.255", "http://192.168.255.255:3100"]
  ])("allows RFC1918 acceptance HTTP origin %s", (_name, apiBase) => {
    expect(buildRuntimeConfig({
      PHOTO_AI_APP_MODE: "acceptance",
      PHOTO_AI_API_BASE: `${apiBase}/`
    })).toEqual({ mode: "acceptance", apiBase });
  });

  it("allows an HTTPS origin for acceptance or production", () => {
    expect(buildRuntimeConfig({
      PHOTO_AI_APP_MODE: "acceptance",
      PHOTO_AI_API_BASE: "https://acceptance.example.com/"
    })).toEqual({
      mode: "acceptance",
      apiBase: "https://acceptance.example.com"
    });
    expect(buildRuntimeConfig({
      PHOTO_AI_APP_MODE: "production",
      PHOTO_AI_API_BASE: "https://api.example.com"
    })).toEqual({
      mode: "production",
      apiBase: "https://api.example.com"
    });
  });

  it.each([
    ["acceptance", "http://127.0.0.1:3100"],
    ["acceptance", "http://example.com"],
    ["acceptance", "http://172.15.255.255:3100"],
    ["acceptance", "http://172.32.0.1:3100"],
    ["acceptance", "http://10.1:3100"],
    ["acceptance", "http://010.0.0.1:3100"],
    ["acceptance", "http://0x0a.0.0.1:3100"],
    ["acceptance", "http://167772161:3100"],
    ["production", "http://192.168.1.20:3100"],
    ["production", "https://user:pass@example.com"],
    ["production", "https://example.com/path"]
  ])("rejects an unsafe %s API origin", (mode, apiBase) => {
    expect(() => buildRuntimeConfig({
      PHOTO_AI_APP_MODE: mode,
      PHOTO_AI_API_BASE: apiBase
    })).toThrow("INVALID_PHOTO_AI_API_BASE");
  });

  it.each([
    [{}, "INVALID_PHOTO_AI_APP_MODE"],
    [{ PHOTO_AI_APP_MODE: "staging" }, "INVALID_PHOTO_AI_APP_MODE"],
    [{ PHOTO_AI_APP_MODE: "acceptance" }, "INVALID_PHOTO_AI_API_BASE"],
    [{
      PHOTO_AI_APP_MODE: "acceptance",
      PHOTO_AI_API_BASE: "not-a-url"
    }, "INVALID_PHOTO_AI_API_BASE"]
  ])("rejects incomplete or malformed environment input", (environment, error) => {
    expect(() => buildRuntimeConfig(environment)).toThrow(error);
  });
});
